# Generated by Django 3.0.6 on 2020-05-30 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='mfd',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
