# Generated by Django 3.0.6 on 2020-05-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200531_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='tet-product'),
            preserve_default=False,
        ),
    ]
