# Generated by Django 3.0.6 on 2020-05-31 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
