# Generated by Django 3.0.6 on 2020-05-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
