# Generated by Django 3.0.6 on 2020-06-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20200617_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='discount_price',
        ),
    ]
