# Generated by Django 3.0.6 on 2020-06-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20200617_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='old_price',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
