# Generated by Django 2.0 on 2020-08-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20200617_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('licence', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
            ],
        ),
    ]
